Allow static libs
COVESA/vsomeip pull request #528
Opened 2023-09-27 16:18 UTC by hefroy

Remove SHARED option from add_library to allow static libs, CMake then respects the standard BUILD_SHARED_LIBS option. Set the default value of BUILD_SHARED_LIBS to ON.

2023-11-10 10:41 UTC, goncaloalmeida commented
we will check this change internally to see if this is causing any other problems
cc @fcmonteiro @DiogoPedrozza

2023-11-10 22:34 UTC, goncaloalmeida requested changes
please rebase/fix merge issues

2023-11-13 08:51 UTC, goncaloalmeida commented
> Rebased ✔️

thanks! I will test this PR internally.

2023-11-13 09:35 UTC, goncaloalmeida requested changes
These changes are not building on the windows env.:
`CMake Error at test/network_tests/CMakeLists.txt:4264 (add_dependencies):
  The dependency target "routingmanagerd" of target "build_network_tests"
  does not exist.`

2023-12-13 14:26 UTC, hefroy commented
> These changes are not building on the windows env.: `CMake Error at test/network_tests/CMakeLists.txt:4264 (add_dependencies): The dependency target "routingmanagerd" of target "build_network_tests" does not exist.`

This seemed to be caused by some other issue on the master branch when I last rebased the branch. I've just rebased it again and now I don't see that CMake error and for me the Windows build compiles ok.

2024-01-04 14:23 UTC, kheaactua commented
I created a similar patch for 3.1.20, I was never really happy with it, but maybe we can compare patches.

I don't remember all the details right now, but my CMake changes were much more extensive, and I had to fix the way the singletons (logger, security, _etc_) were created and remove any lib constructor/destructor.  In the end it seemed to work but I had a segfault on exit in `examples/routingmanagerd`

2024-10-21 12:11 UTC, kheaactua commented
> I created a similar patch for 3.1.20, I was never really happy with it, but maybe we can compare patches.
> 
> I don't remember all the details right now, but my CMake changes were much more extensive, and I had to fix the way the singletons (logger, security, _etc_) were created and remove any lib constructor/destructor. In the end it seemed to work but I had a segfault on exit in `examples/routingmanagerd`

I think the most recent vsomeip release only has [one lib destructor here](https://github.com/search?q=repo%3ACOVESA%2Fvsomeip+__attribute__&type=code, CommonAPI (capicxx-core-runtime) [has two lib constructors though](https://github.com/search?q=repo%3ACOVESA%2Fcapicxx-core-runtime%20__attribute__&type=code) (not sure if you're using CommonAPI)

Looking at the vsomeip one, it could probably be ignored..

2024-12-16 04:42 UTC, hefroy commented
For reference, this patch is being used over in https://github.com/aws/aws-iot-fleetwise-edge
See the patch file here: https://github.com/aws/aws-iot-fleetwise-edge/blob/a6bfb5176eb0a954b436473802de3221b815be7e/tools/patches/vsomeip_allow_static_libs_fix_shutdown_segfaults.patch

2026-04-16 08:11 UTC, closed without merging