Consistently use uid_t/gid_t for credentials
COVESA/vsomeip pull request #561
Opened 2023-11-03 16:50 UTC by kheaactua

2023-12-14 08:14 UTC, goncaloalmeida requested changes
Please rebase

2023-12-14 16:05 UTC, kheaactua commented
> Please rebase

Rebased to 3.4.10 and forced pushed a tweak to `internal_android.hpp`

2023-12-14 18:42 UTC, kheaactua commented
It looks like I hit the Windows build error:
```
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(153,46): error C2039: 'uid_t': is not a member of '`global namespace'' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(153,46): error C2275: 'vsomeip_v3::uid_t': expected an expression instead of a type [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(153,29): error C2923: 'std::numeric_limits': 'vsomeip_v3::uid_t' is not a valid template type argument for parameter '_Ty' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\interface\vsomeip/primitive_types.hpp(60,27): message : see declaration of 'vsomeip_v3::uid_t' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(153,54): error C2955: 'std::numeric_limits': use of class template requires template argument list [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\limits(84,22): message : see declaration of 'std::numeric_limits' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(154,46): error C2039: 'gid_t': is not a member of '`global namespace'' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(154,46): error C2275: 'vsomeip_v3::gid_t': expected an expression instead of a type [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(154,29): error C2923: 'std::numeric_limits': 'vsomeip_v3::gid_t' is not a valid template type argument for parameter '_Ty' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\interface\vsomeip/primitive_types.hpp(61,27): message : see declaration of 'vsomeip_v3::gid_t' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
D:\a\vsomeip\vsomeip\implementation\routing\src\../../configuration/include/internal.hpp(154,54): error C2955: 'std::numeric_limits': use of class template requires template argument list [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\limits(84,22): message : see declaration of 'std::numeric_limits' [D:\a\vsomeip\vsomeip\build\vsomeip3.vcxproj]
```

I'll take a look at this and push a fix.

2023-12-19 20:44 UTC, kheaactua commented
Hi @goncaloalmeida,

PR is rebased, and all the tests pass.

2024-01-04 14:13 UTC, kheaactua commented on implementation/security/src/policy.cpp
I don't like this.  The `reinterpret_cast` is a red flag, and it falsly assumes that the credentials are uints.  I'll push an update.

2024-01-09 15:20 UTC, kheaactua commented
Tweaked the uid/gid deserialization.

@goncaloalmeida

2025-01-30 15:09 UTC, kheaactua commented on implementation/configuration/include/internal.hpp.in
Will do!

2025-01-31 15:10 UTC, duartenfonseca commented on implementation/configuration/include/internal.hpp.in
> +inline constexpr gid_t ANY_GID = (std::numeric_limits<uid_t>::max)();
```suggestion
inline constexpr gid_t ANY_GID = (std::numeric_limits<gid_t>::max)();
```

2025-01-31 15:12 UTC, duartenfonseca commented on implementation/security/src/policy_manager_impl.cpp
> +    gid_t its_uid(ANY_UID), its_gid(ANY_GID);
```suggestion
    uid_t its_uid(ANY_UID);
    gid_t its_gid(ANY_GID);
```

2025-01-31 16:46 UTC, kheaactua commented on implementation/configuration/include/internal_android.hpp
> +inline constexpr gid_t ANY_GID = (std::numeric_limits<uid_t>::max)();
oops, fixing that now

2025-01-31 16:49 UTC, kheaactua commented on implementation/configuration/include/internal_android.hpp
> +inline constexpr gid_t ANY_GID = (std::numeric_limits<uid_t>::max)();
fixed in 856700a14

2025-01-31 16:51 UTC, kheaactua commented on implementation/security/src/policy_manager_impl.cpp
> +    gid_t its_uid(ANY_UID), its_gid(ANY_GID);
fixed in b8bbeaa3

2025-02-19 19:02 UTC, merged