E2E: Invent support for E2E Profile 05.
COVESA/vsomeip pull request #589
Opened 2023-12-15 13:18 UTC by brenkem

As requested under [1] I split the P05 from the PR and add the changes here to a new PR.

This PR adds support for the E2E Profile 05, that we added and tested in our project.

Please check to merge the changes or request changes if needed. Thanks.

[1]:
https://github.com/COVESA/vsomeip/pull/565

2023-12-18 14:09 UTC, sgpires requested changes

2023-12-18 14:09 UTC, sgpires commented on implementation/e2e_protection/include/e2e/profile/profile05/profile_05.hpp
> +    profile_config(uint32_t _data_id, size_t _offset,
Profile 05 does not require _min_data_length nor _max_data_length. Instead, it uses a fixed data length. The necessary parameters can be found [here](https://www.autosar.org/fileadmin/standards/R20-11/FO/AUTOSAR_PRS_E2EProtocol.pdf#chapter.8)

2023-12-18 14:09 UTC, sgpires commented on implementation/e2e_protection/include/e2e/profile/profile05/protector.hpp
> +    void write_32(e2e_buffer &_buffer, uint32_t _data, size_t _index);
This method is not used anywhere, it can be removed

2023-12-18 14:09 UTC, sgpires commented on implementation/e2e_protection/src/e2e/profile/e2e_provider_impl.cpp
> +    size_t min_data_length = read_value_from_config<size_t>(_config,
min_data_length and max_data_length are not parameters of profile 05, instead use just dataLength

2023-12-18 14:09 UTC, sgpires commented on implementation/e2e_protection/src/e2e/profile/profile05/checker.cpp
> +profile_05_checker::verify_input(const e2e_buffer &_buffer) const {
The verify_input method should be checking the fixed dataLength

2023-12-18 14:09 UTC, sgpires commented on implementation/e2e_protection/src/e2e/profile/profile05/protector.cpp
> +protector::verify_inputs(e2e_buffer &_buffer) {
The verify_input method should be checking the fixed dataLength

2023-12-18 17:15 UTC, brenkem commented
I added the requested changes. Please check and let me know if anything else needs to be fixed.

Thanks.

2023-12-19 09:33 UTC, sgpires approved these changes

2023-12-20 10:10 UTC, goncaloalmeida approved these changes

2023-12-20 16:32 UTC, merged